version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "never" 

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "never" 

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "never" 

  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "never"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "never"
