x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.12"
  INSTALL_NODE_VERSION: "20"

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./data:/app/data
    - ./logs:/app/logs

services:
  flask-dev:
    user: "112:1003"
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "audiorate-development"
    ports:
      - "8080:5000"
      - "2992:2992"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    <<: *default_volumes

  flask-prod:
    user: "112:1003"
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "audiorate-production"
    ports:
      - "8080:5000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "audiorate-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

volumes:
  node-modules:
