x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.12"
  INSTALL_NODE_VERSION: "20"

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./data:/app/data
    - ./logs:/app/logs

services:
  flask-dev:
    user: "1000:1000"
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "audiorate-development"
    ports:
      - "8081:5000"
      - "2992:2992"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    <<: *default_volumes

  flask-prod:
    user: "112:1003"
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "audiorate-production"
    ports:
      - "8080:5000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes
    depends_on:
      - cloudflared
    networks:
      - cloudflare-internal
      - default # Keep the default network for other potential host access 

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "audiorate-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes
  cloudflared:
    container_name: cloudflared_tunnel
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      cloudflare-internal:
        ipv4_address: 172.30.10.2 # Assign a static IP (optional but can be helpful)
      default:

volumes:
  node-modules:

networks:
  cloudflare-internal:
    internal: true
    ipam:
      config:
        - subnet: 172.30.10.0/24 # Choose a different subnet than your other internal network
  default:    
    
