"""empty message

Revision ID: 2f16429c8017
Revises: 
Create Date: 2025-04-05 14:57:36.951557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f16429c8017'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_sessions_session_hash'), ['session_hash'], unique=False)

    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file', sa.String(length=100), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['rating_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'model_id', 'sample_id', name='uq_session_model_sample')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_ratings')
    op.drop_table('samples')
    with op.batch_alter_table('rating_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_sessions_session_hash'))

    op.drop_table('rating_sessions')
    op.drop_table('models')
    # ### end Alembic commands ###
